# Change these first
owner: bendevjunior # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: matogrossototal.com
    url: https://matogrossototal.com
  - name: pedidomesa.com
    url: https://pedidomesa.com
  - name: portalmichalak.com.br
    url: https://portalmichalak.com.br

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bendevoficial.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bendev Studio
  introTitle: "**Status dos Serviços da Bendev Studio**"
  introMessage: "Acompanhe a disponibilidade e integridade dos nossos sistemas e APIs. Atualizado em tempo real."
  navbar:
    - title: Status
      href: /
    - title: Nosso Site
      href: https://bendevstudio.com
    - title: Pedido Mesa
      href: https://pedidomesa.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
