name: Run Uptime Now

on:
  workflow_dispatch:

jobs:
  run-uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Run Upptime monitor
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
